doctrine:
    dbal:
        host:             '%env(DATABASE_HOST)%'
        port:             '%env(DATABASE_PORT)%'
        dbname:           '%env(DATABASE_NAME)%'
        user:             '%env(DATABASE_USERNAME)%'
        password:         '%env(DATABASE_PASSWORD)%'
        server_version:   '%env(DATABASE_SERVER_VERSION)%'
        #url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        filters:
#            softdeleteable:
#                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
#                enabled: true
            deleted_at_filter:
                class:   App\Filter\DeletedAtFilter
                enabled: true
            users_filter:
                class:   App\Filter\UsersFilter
                enabled: true
            find_in_set_filter:
                class:   App\Filter\FindInSetFilter
                enabled: true