snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%"
        cache:
            type: predis
            alias: cache
            dsn: "%env(REDIS_URL)%"
            logging: false
            options:
                prefix : "ivnews:api:cache:%env(APP_ENV)%:"
        session:
            type: predis
            alias: session
            dsn: "%env(REDIS_URL)%"
            logging: false
            options:
                prefix : "ivnews:session:%env(APP_ENV)%:"
    session:
        client: session
#    doctrine:
#        metadata_cache:
#            client: cache
#            entity_manager: default          # the name of your entity_manager connection
#        result_cache:
#            client: cache
#            entity_manager: [default, read]  # you may specify multiple entity_managers
#        query_cache:
#            client: cache
#            entity_manager: default
#        second_level_cache:
#            client: cache
#            entity_manager: default
