-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQguB24Y0EHzaRbGWRq
6PBjCYXIOk/rGVBmsxsuQk+7U5igCgYIKoZIzj0DAQehRANCAASNkyDRFVXZeiA9
Nl9TM5v1AFdWSCzUAk3p9igG3AjcanVRfaPT3Yq40/sCLDL3dxARVu/xlGRTwQH3
lPCUrfnF
-----END PRIVATE KEY-----