FROM php:7.4-fpm-alpine3.13

RUN apk add --update --no-cache $PHPIZE_DEPS zlib-dev autoconf gcc g++ make linux-headers \
        && pecl install apcu \
        && CPPFLAGS="-Wno-maybe-uninitialized" pecl install grpc \
        && docker-php-ext-enable apcu grpc

RUN docker-php-ext-install -j$(nproc) pdo_mysql pcntl opcache

# COPY php-fpm configs
COPY php-fpm/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY php-fpm/default.ini /usr/local/etc/php/conf.d/default.ini

# Install Supervisor.
RUN apk add supervisor mediainfo

# Define working directory.
WORKDIR /etc/supervisor/conf.d

#COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
# Start supervisor, define default command.
CMD ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

EXPOSE 9001
