FROM php:7.4
RUN apt-get update -yqq
RUN apt-get install -yqq git libmcrypt-dev libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev libzip-dev libonig-dev autoconf
RUN pecl install redis grpc
RUN docker-php-ext-enable redis
RUN docker-php-ext-enable grpc
RUN docker-php-ext-install mbstring pdo pdo_pgsql curl json intl gd xml zip bz2 opcache pdo_sqlite pdo_mysql
RUN pecl install xdebug
RUN docker-php-ext-enable xdebug