<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>endpoints.events.AddShowRequest</code>
 */
class AddShowRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string show_name = 1;</code>
     */
    protected $show_name = '';
    /**
     * Generated from protobuf field <code>string created_by = 2;</code>
     */
    protected $created_by = '';
    /**
     * Generated from protobuf field <code>string vnp_id = 3;</code>
     */
    protected $vnp_id = '';
    /**
     * Generated from protobuf field <code>repeated .endpoints.events.DelayNewsMarketListHelper delay_news_market_list = 4;</code>
     */
    private $delay_news_market_list;
    /**
     * Generated from protobuf field <code>float length = 5;</code>
     */
    protected $length = 0.0;
    /**
     * Generated from protobuf field <code>string source_id = 6;</code>
     */
    protected $source_id = '';
    /**
     * Generated from protobuf field <code>repeated .endpoints.events.LocalDropInsHelper local_drop_ins = 7;</code>
     */
    private $local_drop_ins;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $show_name
     *     @type string $created_by
     *     @type string $vnp_id
     *     @type \Endpoints\Events\DelayNewsMarketListHelper[]|\Google\Protobuf\Internal\RepeatedField $delay_news_market_list
     *     @type float $length
     *     @type string $source_id
     *     @type \Endpoints\Events\LocalDropInsHelper[]|\Google\Protobuf\Internal\RepeatedField $local_drop_ins
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string show_name = 1;</code>
     * @return string
     */
    public function getShowName()
    {
        return $this->show_name;
    }

    /**
     * Generated from protobuf field <code>string show_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setShowName($var)
    {
        GPBUtil::checkString($var, True);
        $this->show_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_by = 2;</code>
     * @return string
     */
    public function getCreatedBy()
    {
        return $this->created_by;
    }

    /**
     * Generated from protobuf field <code>string created_by = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedBy($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vnp_id = 3;</code>
     * @return string
     */
    public function getVnpId()
    {
        return $this->vnp_id;
    }

    /**
     * Generated from protobuf field <code>string vnp_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVnpId($var)
    {
        GPBUtil::checkString($var, True);
        $this->vnp_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .endpoints.events.DelayNewsMarketListHelper delay_news_market_list = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDelayNewsMarketList()
    {
        return $this->delay_news_market_list;
    }

    /**
     * Generated from protobuf field <code>repeated .endpoints.events.DelayNewsMarketListHelper delay_news_market_list = 4;</code>
     * @param \Endpoints\Events\DelayNewsMarketListHelper[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDelayNewsMarketList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Endpoints\Events\DelayNewsMarketListHelper::class);
        $this->delay_news_market_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float length = 5;</code>
     * @return float
     */
    public function getLength()
    {
        return $this->length;
    }

    /**
     * Generated from protobuf field <code>float length = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setLength($var)
    {
        GPBUtil::checkFloat($var);
        $this->length = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string source_id = 6;</code>
     * @return string
     */
    public function getSourceId()
    {
        return $this->source_id;
    }

    /**
     * Generated from protobuf field <code>string source_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .endpoints.events.LocalDropInsHelper local_drop_ins = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLocalDropIns()
    {
        return $this->local_drop_ins;
    }

    /**
     * Generated from protobuf field <code>repeated .endpoints.events.LocalDropInsHelper local_drop_ins = 7;</code>
     * @param \Endpoints\Events\LocalDropInsHelper[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLocalDropIns($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Endpoints\Events\LocalDropInsHelper::class);
        $this->local_drop_ins = $arr;

        return $this;
    }

}

