<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>endpoints.events.AddSourceVideoRequest</code>
 */
class AddSourceVideoRequest extends \Google\Protobuf\Internal\Message
{
    protected $show_oneof;
    protected $publish_date_time_oneof;
    protected $video_link_oneof;
    protected $cc_link_oneof;
    protected $vnp_id_oneof;
    protected $source_oneof;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $show
     *     @type string $publish_date_time
     *     @type string $video_link
     *     @type string $CC_link
     *     @type string $vnp_id
     *     @type string $source
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string show = 1;</code>
     * @return string
     */
    public function getShow()
    {
        return $this->readOneof(1);
    }

    public function hasShow()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>string show = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setShow($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string publish_date_time = 2;</code>
     * @return string
     */
    public function getPublishDateTime()
    {
        return $this->readOneof(2);
    }

    public function hasPublishDateTime()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>string publish_date_time = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPublishDateTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string video_link = 3;</code>
     * @return string
     */
    public function getVideoLink()
    {
        return $this->readOneof(3);
    }

    public function hasVideoLink()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>string video_link = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVideoLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string CC_link = 4;</code>
     * @return string
     */
    public function getCCLink()
    {
        return $this->readOneof(4);
    }

    public function hasCCLink()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>string CC_link = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCCLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vnp_id = 5;</code>
     * @return string
     */
    public function getVnpId()
    {
        return $this->readOneof(5);
    }

    public function hasVnpId()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>string vnp_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setVnpId($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string source = 6;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->readOneof(6);
    }

    public function hasSource()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>string source = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getShowOneof()
    {
        return $this->whichOneof("show_oneof");
    }

    /**
     * @return string
     */
    public function getPublishDateTimeOneof()
    {
        return $this->whichOneof("publish_date_time_oneof");
    }

    /**
     * @return string
     */
    public function getVideoLinkOneof()
    {
        return $this->whichOneof("video_link_oneof");
    }

    /**
     * @return string
     */
    public function getCcLinkOneof()
    {
        return $this->whichOneof("cc_link_oneof");
    }

    /**
     * @return string
     */
    public function getVnpIdOneof()
    {
        return $this->whichOneof("vnp_id_oneof");
    }

    /**
     * @return string
     */
    public function getSourceOneof()
    {
        return $this->whichOneof("source_oneof");
    }

}

