<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Admins can add new sources to the VNE.
 *Sample Request body:
 *{
 * source_name': 'HBO',
 * dma_list:['San Jose', 'Los Angeles', 'New York],
 * created_by:'William'
 *}
 *
 * Generated from protobuf message <code>endpoints.events.AddSourceRequest</code>
 */
class AddSourceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *Source Name
     *
     * Generated from protobuf field <code>string source_name = 1;</code>
     */
    protected $source_name = '';
    /**
     *List of DMA
     *
     * Generated from protobuf field <code>repeated string news_market_list = 2;</code>
     */
    private $news_market_list;
    /**
     *Creator Name
     *
     * Generated from protobuf field <code>string created_by = 3;</code>
     */
    protected $created_by = '';
    /**
     *VNP id
     *
     * Generated from protobuf field <code>string vnp_id = 4;</code>
     */
    protected $vnp_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $source_name
     *          Source Name
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $news_market_list
     *          List of DMA
     *     @type string $created_by
     *          Creator Name
     *     @type string $vnp_id
     *          VNP id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     *Source Name
     *
     * Generated from protobuf field <code>string source_name = 1;</code>
     * @return string
     */
    public function getSourceName()
    {
        return $this->source_name;
    }

    /**
     *Source Name
     *
     * Generated from protobuf field <code>string source_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_name = $var;

        return $this;
    }

    /**
     *List of DMA
     *
     * Generated from protobuf field <code>repeated string news_market_list = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNewsMarketList()
    {
        return $this->news_market_list;
    }

    /**
     *List of DMA
     *
     * Generated from protobuf field <code>repeated string news_market_list = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNewsMarketList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->news_market_list = $arr;

        return $this;
    }

    /**
     *Creator Name
     *
     * Generated from protobuf field <code>string created_by = 3;</code>
     * @return string
     */
    public function getCreatedBy()
    {
        return $this->created_by;
    }

    /**
     *Creator Name
     *
     * Generated from protobuf field <code>string created_by = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedBy($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_by = $var;

        return $this;
    }

    /**
     *VNP id
     *
     * Generated from protobuf field <code>string vnp_id = 4;</code>
     * @return string
     */
    public function getVnpId()
    {
        return $this->vnp_id;
    }

    /**
     *VNP id
     *
     * Generated from protobuf field <code>string vnp_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setVnpId($var)
    {
        GPBUtil::checkString($var, True);
        $this->vnp_id = $var;

        return $this;
    }

}

