<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>endpoints.events.DelayNewsMarketListHelper</code>
 */
class DelayNewsMarketListHelper extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float delay = 1;</code>
     */
    protected $delay = 0.0;
    /**
     * Generated from protobuf field <code>string newsMarket = 2;</code>
     */
    protected $newsMarket = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $delay
     *     @type string $newsMarket
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float delay = 1;</code>
     * @return float
     */
    public function getDelay()
    {
        return $this->delay;
    }

    /**
     * Generated from protobuf field <code>float delay = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setDelay($var)
    {
        GPBUtil::checkFloat($var);
        $this->delay = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string newsMarket = 2;</code>
     * @return string
     */
    public function getNewsMarket()
    {
        return $this->newsMarket;
    }

    /**
     * Generated from protobuf field <code>string newsMarket = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNewsMarket($var)
    {
        GPBUtil::checkString($var, True);
        $this->newsMarket = $var;

        return $this;
    }

}

