<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>endpoints.events.DeleteSeriesRequest</code>
 */
class DeleteSeriesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string vnp_id = 1;</code>
     */
    protected $vnp_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $vnp_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string vnp_id = 1;</code>
     * @return string
     */
    public function getVnpId()
    {
        return $this->vnp_id;
    }

    /**
     * Generated from protobuf field <code>string vnp_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVnpId($var)
    {
        GPBUtil::checkString($var, True);
        $this->vnp_id = $var;

        return $this;
    }

}

