<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>endpoints.events.DeleteSourceNewsMarketRequest</code>
 */
class DeleteSourceNewsMarketRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string news_market_list = 1;</code>
     */
    private $news_market_list;
    /**
     * Generated from protobuf field <code>string source_name = 2;</code>
     */
    protected $source_name = '';
    /**
     * Generated from protobuf field <code>string vnp_id = 3;</code>
     */
    protected $vnp_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $news_market_list
     *     @type string $source_name
     *     @type string $vnp_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string news_market_list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNewsMarketList()
    {
        return $this->news_market_list;
    }

    /**
     * Generated from protobuf field <code>repeated string news_market_list = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNewsMarketList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->news_market_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string source_name = 2;</code>
     * @return string
     */
    public function getSourceName()
    {
        return $this->source_name;
    }

    /**
     * Generated from protobuf field <code>string source_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vnp_id = 3;</code>
     * @return string
     */
    public function getVnpId()
    {
        return $this->vnp_id;
    }

    /**
     * Generated from protobuf field <code>string vnp_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVnpId($var)
    {
        GPBUtil::checkString($var, True);
        $this->vnp_id = $var;

        return $this;
    }

}

