<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>endpoints.events.DeleteStoryTypeRequest</code>
 */
class DeleteStoryTypeRequest extends \Google\Protobuf\Internal\Message
{
    protected $vne_id_oneof;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $vne_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string vne_id = 1;</code>
     * @return string
     */
    public function getVneId()
    {
        return $this->readOneof(1);
    }

    public function hasVneId()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>string vne_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVneId($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getVneIdOneof()
    {
        return $this->whichOneof("vne_id_oneof");
    }

}

