<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>endpoints.events.DeleteSourceVideoRequest</code>
 */
class DeleteSourceVideoRequest extends \Google\Protobuf\Internal\Message
{
    protected $vnp_id_oneof;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $vnp_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string vnp_id = 5;</code>
     * @return string
     */
    public function getVnpId()
    {
        return $this->readOneof(5);
    }

    public function hasVnpId()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>string vnp_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setVnpId($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getVnpIdOneof()
    {
        return $this->whichOneof("vnp_id_oneof");
    }

}

