<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * VNP can edit the DMAs
 * {
 *   'dma_name': 'Los Angeles',
 *   'new_dma_name': 'San Jose'
 * }
 *
 * Generated from protobuf message <code>endpoints.events.EditNewsMarketNameRequest</code>
 */
class EditNewsMarketNameRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *DMA name
     *
     * Generated from protobuf field <code>string news_market_name = 1;</code>
     */
    protected $news_market_name = '';
    /**
     *New DMA name
     *
     * Generated from protobuf field <code>string new_news_market_name = 2;</code>
     */
    protected $new_news_market_name = '';
    /**
     * Generated from protobuf field <code>string vne_id = 3;</code>
     */
    protected $vne_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $news_market_name
     *          DMA name
     *     @type string $new_news_market_name
     *          New DMA name
     *     @type string $vne_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     *DMA name
     *
     * Generated from protobuf field <code>string news_market_name = 1;</code>
     * @return string
     */
    public function getNewsMarketName()
    {
        return $this->news_market_name;
    }

    /**
     *DMA name
     *
     * Generated from protobuf field <code>string news_market_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setNewsMarketName($var)
    {
        GPBUtil::checkString($var, True);
        $this->news_market_name = $var;

        return $this;
    }

    /**
     *New DMA name
     *
     * Generated from protobuf field <code>string new_news_market_name = 2;</code>
     * @return string
     */
    public function getNewNewsMarketName()
    {
        return $this->new_news_market_name;
    }

    /**
     *New DMA name
     *
     * Generated from protobuf field <code>string new_news_market_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNewNewsMarketName($var)
    {
        GPBUtil::checkString($var, True);
        $this->new_news_market_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vne_id = 3;</code>
     * @return string
     */
    public function getVneId()
    {
        return $this->vne_id;
    }

    /**
     * Generated from protobuf field <code>string vne_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVneId($var)
    {
        GPBUtil::checkString($var, True);
        $this->vne_id = $var;

        return $this;
    }

}

