<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>endpoints.events.EditShowRequest</code>
 */
class EditShowRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .endpoints.events.ChangedLocalDropInsHelper changed_local_drop_ins = 1;</code>
     */
    private $changed_local_drop_ins;
    /**
     * Generated from protobuf field <code>string changed_show_name = 2;</code>
     */
    protected $changed_show_name = '';
    /**
     * Generated from protobuf field <code>repeated .endpoints.events.ChangedDelayNewsMarketListHelper changed_delay_news_market_list = 4;</code>
     */
    private $changed_delay_news_market_list;
    /**
     * Generated from protobuf field <code>string changed_source_id = 5;</code>
     */
    protected $changed_source_id = '';
    protected $vnp_id_oneof;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Endpoints\Events\ChangedLocalDropInsHelper[]|\Google\Protobuf\Internal\RepeatedField $changed_local_drop_ins
     *     @type string $changed_show_name
     *     @type string $vnp_id
     *     @type \Endpoints\Events\ChangedDelayNewsMarketListHelper[]|\Google\Protobuf\Internal\RepeatedField $changed_delay_news_market_list
     *     @type string $changed_source_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .endpoints.events.ChangedLocalDropInsHelper changed_local_drop_ins = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChangedLocalDropIns()
    {
        return $this->changed_local_drop_ins;
    }

    /**
     * Generated from protobuf field <code>repeated .endpoints.events.ChangedLocalDropInsHelper changed_local_drop_ins = 1;</code>
     * @param \Endpoints\Events\ChangedLocalDropInsHelper[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChangedLocalDropIns($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Endpoints\Events\ChangedLocalDropInsHelper::class);
        $this->changed_local_drop_ins = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string changed_show_name = 2;</code>
     * @return string
     */
    public function getChangedShowName()
    {
        return $this->changed_show_name;
    }

    /**
     * Generated from protobuf field <code>string changed_show_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setChangedShowName($var)
    {
        GPBUtil::checkString($var, True);
        $this->changed_show_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vnp_id = 3;</code>
     * @return string
     */
    public function getVnpId()
    {
        return $this->readOneof(3);
    }

    public function hasVnpId()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>string vnp_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVnpId($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .endpoints.events.ChangedDelayNewsMarketListHelper changed_delay_news_market_list = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChangedDelayNewsMarketList()
    {
        return $this->changed_delay_news_market_list;
    }

    /**
     * Generated from protobuf field <code>repeated .endpoints.events.ChangedDelayNewsMarketListHelper changed_delay_news_market_list = 4;</code>
     * @param \Endpoints\Events\ChangedDelayNewsMarketListHelper[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChangedDelayNewsMarketList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Endpoints\Events\ChangedDelayNewsMarketListHelper::class);
        $this->changed_delay_news_market_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string changed_source_id = 5;</code>
     * @return string
     */
    public function getChangedSourceId()
    {
        return $this->changed_source_id;
    }

    /**
     * Generated from protobuf field <code>string changed_source_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setChangedSourceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->changed_source_id = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getVnpIdOneof()
    {
        return $this->whichOneof("vnp_id_oneof");
    }

}

