<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * VNP can edit the DMAs
 * {
 *   'dma_name': 'Los Angeles',
 *   'new_dma_name': 'San Jose'
 * }
 *
 * Generated from protobuf message <code>endpoints.events.EditDMANameRequest</code>
 */
class EditDMANameRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *DMA name
     *
     * Generated from protobuf field <code>string dma_name = 1;</code>
     */
    protected $dma_name = '';
    /**
     *New DMA name
     *
     * Generated from protobuf field <code>string new_dma_name = 2;</code>
     */
    protected $new_dma_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $dma_name
     *          DMA name
     *     @type string $new_dma_name
     *          New DMA name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     *DMA name
     *
     * Generated from protobuf field <code>string dma_name = 1;</code>
     * @return string
     */
    public function getDmaName()
    {
        return $this->dma_name;
    }

    /**
     *DMA name
     *
     * Generated from protobuf field <code>string dma_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDmaName($var)
    {
        GPBUtil::checkString($var, True);
        $this->dma_name = $var;

        return $this;
    }

    /**
     *New DMA name
     *
     * Generated from protobuf field <code>string new_dma_name = 2;</code>
     * @return string
     */
    public function getNewDmaName()
    {
        return $this->new_dma_name;
    }

    /**
     *New DMA name
     *
     * Generated from protobuf field <code>string new_dma_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNewDmaName($var)
    {
        GPBUtil::checkString($var, True);
        $this->new_dma_name = $var;

        return $this;
    }

}

