<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>endpoints.events.EditSourceVideoRequest</code>
 */
class EditSourceVideoRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string show = 1;</code>
     */
    protected $show = '';
    /**
     * Generated from protobuf field <code>string publish_date_time = 2;</code>
     */
    protected $publish_date_time = '';
    /**
     * Generated from protobuf field <code>string video_link = 3;</code>
     */
    protected $video_link = '';
    /**
     * Generated from protobuf field <code>string CC_link = 4;</code>
     */
    protected $CC_link = '';
    /**
     * Generated from protobuf field <code>string source = 6;</code>
     */
    protected $source = '';
    protected $vnp_id_oneof;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $show
     *     @type string $publish_date_time
     *     @type string $video_link
     *     @type string $CC_link
     *     @type string $vnp_id
     *     @type string $source
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string show = 1;</code>
     * @return string
     */
    public function getShow()
    {
        return $this->show;
    }

    /**
     * Generated from protobuf field <code>string show = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setShow($var)
    {
        GPBUtil::checkString($var, True);
        $this->show = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string publish_date_time = 2;</code>
     * @return string
     */
    public function getPublishDateTime()
    {
        return $this->publish_date_time;
    }

    /**
     * Generated from protobuf field <code>string publish_date_time = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPublishDateTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->publish_date_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string video_link = 3;</code>
     * @return string
     */
    public function getVideoLink()
    {
        return $this->video_link;
    }

    /**
     * Generated from protobuf field <code>string video_link = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVideoLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->video_link = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string CC_link = 4;</code>
     * @return string
     */
    public function getCCLink()
    {
        return $this->CC_link;
    }

    /**
     * Generated from protobuf field <code>string CC_link = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCCLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->CC_link = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vnp_id = 5;</code>
     * @return string
     */
    public function getVnpId()
    {
        return $this->readOneof(5);
    }

    public function hasVnpId()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>string vnp_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setVnpId($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string source = 6;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * Generated from protobuf field <code>string source = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getVnpIdOneof()
    {
        return $this->whichOneof("vnp_id_oneof");
    }

}

