<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Admins can change the name of the source.
 *Sample Request body:
 *{
 * 'source_name': 'HBO'
 * 'new_source_name':'Netflix'
 *}
 *
 * Generated from protobuf message <code>endpoints.events.EditSourceRequest</code>
 */
class EditSourceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *New source name
     *
     * Generated from protobuf field <code>string new_source_name = 2;</code>
     */
    protected $new_source_name = '';
    /**
     * Generated from protobuf field <code>string vnp_id = 3;</code>
     */
    protected $vnp_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $new_source_name
     *          New source name
     *     @type string $vnp_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     *New source name
     *
     * Generated from protobuf field <code>string new_source_name = 2;</code>
     * @return string
     */
    public function getNewSourceName()
    {
        return $this->new_source_name;
    }

    /**
     *New source name
     *
     * Generated from protobuf field <code>string new_source_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNewSourceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->new_source_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vnp_id = 3;</code>
     * @return string
     */
    public function getVnpId()
    {
        return $this->vnp_id;
    }

    /**
     * Generated from protobuf field <code>string vnp_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVnpId($var)
    {
        GPBUtil::checkString($var, True);
        $this->vnp_id = $var;

        return $this;
    }

}

