<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>endpoints.events.GetCountiesReplyhelper</code>
 */
class GetCountiesReplyhelper extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string County_name = 2;</code>
     */
    protected $County_name = '';
    /**
     * Generated from protobuf field <code>string State_name = 3;</code>
     */
    protected $State_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $County_name
     *     @type string $State_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string County_name = 2;</code>
     * @return string
     */
    public function getCountyName()
    {
        return $this->County_name;
    }

    /**
     * Generated from protobuf field <code>string County_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCountyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->County_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string State_name = 3;</code>
     * @return string
     */
    public function getStateName()
    {
        return $this->State_name;
    }

    /**
     * Generated from protobuf field <code>string State_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStateName($var)
    {
        GPBUtil::checkString($var, True);
        $this->State_name = $var;

        return $this;
    }

}

