<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The reply containing the message from VNE.
 *Sample Reply body:
 *{
 * 'dma_list': [
 * {'VNP_id': 669, 'DMA_name': 'MADISON'},
 * {'VNP_id': 628, 'DMA_name': 'MONROE-EL DORADO'},
 * {'VNP_id': 632, 'DMA_name': 'PADUCAH-CAPE GIRARDEAU-HARRISBURG'},
 * {'VNP_id': 504, 'DMA_name': 'PHILADELPHIA'},
 * {'VNP_id': 657, 'DMA_name': 'SHERMAN-ADA'}
 * ],
 * 'remaining_dma': 1}
 *
 * Generated from protobuf message <code>endpoints.events.GetDMAReply</code>
 */
class GetDMAReply extends \Google\Protobuf\Internal\Message
{
    /**
     *DMA list contain vnp id and dma name
     *
     * Generated from protobuf field <code>repeated .endpoints.events.dma_list_helper dma_list = 1;</code>
     */
    private $dma_list;
    /**
     *Number of dma left
     *
     * Generated from protobuf field <code>int32 remaining_dma = 2;</code>
     */
    protected $remaining_dma = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Endpoints\Events\dma_list_helper[]|\Google\Protobuf\Internal\RepeatedField $dma_list
     *          DMA list contain vnp id and dma name
     *     @type int $remaining_dma
     *          Number of dma left
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     *DMA list contain vnp id and dma name
     *
     * Generated from protobuf field <code>repeated .endpoints.events.dma_list_helper dma_list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDmaList()
    {
        return $this->dma_list;
    }

    /**
     *DMA list contain vnp id and dma name
     *
     * Generated from protobuf field <code>repeated .endpoints.events.dma_list_helper dma_list = 1;</code>
     * @param \Endpoints\Events\dma_list_helper[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDmaList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Endpoints\Events\dma_list_helper::class);
        $this->dma_list = $arr;

        return $this;
    }

    /**
     *Number of dma left
     *
     * Generated from protobuf field <code>int32 remaining_dma = 2;</code>
     * @return int
     */
    public function getRemainingDma()
    {
        return $this->remaining_dma;
    }

    /**
     *Number of dma left
     *
     * Generated from protobuf field <code>int32 remaining_dma = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRemainingDma($var)
    {
        GPBUtil::checkInt32($var);
        $this->remaining_dma = $var;

        return $this;
    }

}

