<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

if (false) {
    /**
     * This class is deprecated. Use Endpoints\Events\GetDMAReply\DMA\County instead.
     * @deprecated
     */
    class GetDMAReply_DMA_County {}
}
class_exists(GetDMAReply\DMA\County::class);
@trigger_error('Endpoints\Events\GetDMAReply_DMA_County is deprecated and will be removed in the next major release. Use Endpoints\Events\GetDMAReply\DMA\County instead', E_USER_DEPRECATED);

