<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>endpoints.events.GetHighLevelSubjectReply</code>
 */
class GetHighLevelSubjectReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .endpoints.events.GetHighLevelSubjectReplyHelper high_level_subject_list = 1;</code>
     */
    private $high_level_subject_list;
    /**
     * Generated from protobuf field <code>string status = 2;</code>
     */
    protected $status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Endpoints\Events\GetHighLevelSubjectReplyHelper[]|\Google\Protobuf\Internal\RepeatedField $high_level_subject_list
     *     @type string $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .endpoints.events.GetHighLevelSubjectReplyHelper high_level_subject_list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHighLevelSubjectList()
    {
        return $this->high_level_subject_list;
    }

    /**
     * Generated from protobuf field <code>repeated .endpoints.events.GetHighLevelSubjectReplyHelper high_level_subject_list = 1;</code>
     * @param \Endpoints\Events\GetHighLevelSubjectReplyHelper[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHighLevelSubjectList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Endpoints\Events\GetHighLevelSubjectReplyHelper::class);
        $this->high_level_subject_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 2;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

}

