<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>endpoints.events.GetNodeRequest</code>
 */
class GetNodeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string node_label = 1;</code>
     */
    protected $node_label = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $node_label
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string node_label = 1;</code>
     * @return string
     */
    public function getNodeLabel()
    {
        return $this->node_label;
    }

    /**
     * Generated from protobuf field <code>string node_label = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setNodeLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->node_label = $var;

        return $this;
    }

}

