<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>endpoints.events.GetPreferencesReply</code>
 */
class GetPreferencesReply extends \Google\Protobuf\Internal\Message
{
    /**
     *List of user preferences
     *
     * Generated from protobuf field <code>.endpoints.events.GetPreferencesReplyHelper preferences = 1;</code>
     */
    protected $preferences = null;
    /**
     * Generated from protobuf field <code>string status = 3;</code>
     */
    protected $status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Endpoints\Events\GetPreferencesReplyHelper $preferences
     *          List of user preferences
     *     @type string $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     *List of user preferences
     *
     * Generated from protobuf field <code>.endpoints.events.GetPreferencesReplyHelper preferences = 1;</code>
     * @return \Endpoints\Events\GetPreferencesReplyHelper|null
     */
    public function getPreferences()
    {
        return isset($this->preferences) ? $this->preferences : null;
    }

    public function hasPreferences()
    {
        return isset($this->preferences);
    }

    public function clearPreferences()
    {
        unset($this->preferences);
    }

    /**
     *List of user preferences
     *
     * Generated from protobuf field <code>.endpoints.events.GetPreferencesReplyHelper preferences = 1;</code>
     * @param \Endpoints\Events\GetPreferencesReplyHelper $var
     * @return $this
     */
    public function setPreferences($var)
    {
        GPBUtil::checkMessage($var, \Endpoints\Events\GetPreferencesReplyHelper::class);
        $this->preferences = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 3;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

}

