<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The reply containing the message from VNE.
 *Sample Reply body:
 *{
 * 'preferences': ['pref_source_entity', 'not_pref_source_entity', 'pref_subject', 'not_pref_subject', 'pref_words_entity', 'not_pref_words_entity', 'pref_location', 'not_pref_location']
 *}
 *
 * Generated from protobuf message <code>endpoints.events.GetPreferencesReplyHelper</code>
 */
class GetPreferencesReplyHelper extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string pref_source_entity = 1;</code>
     */
    private $pref_source_entity;
    /**
     * Generated from protobuf field <code>repeated string not_pref_source_entity = 2;</code>
     */
    private $not_pref_source_entity;
    /**
     * Generated from protobuf field <code>repeated string pref_highlevel_subject = 3;</code>
     */
    private $pref_highlevel_subject;
    /**
     * Generated from protobuf field <code>repeated string not_pref_highlevel_subject = 4;</code>
     */
    private $not_pref_highlevel_subject;
    /**
     * Generated from protobuf field <code>repeated string pref_people_organization = 5;</code>
     */
    private $pref_people_organization;
    /**
     * Generated from protobuf field <code>repeated string not_pref_people_organization = 6;</code>
     */
    private $not_pref_people_organization;
    /**
     * Generated from protobuf field <code>repeated string pref_geo = 7;</code>
     */
    private $pref_geo;
    /**
     * Generated from protobuf field <code>repeated string not_pref_geo = 8;</code>
     */
    private $not_pref_geo;
    /**
     * Generated from protobuf field <code>repeated string pref_personal_interest = 9;</code>
     */
    private $pref_personal_interest;
    /**
     * Generated from protobuf field <code>repeated string pref_subjects = 10;</code>
     */
    private $pref_subjects;
    /**
     * Generated from protobuf field <code>repeated string not_pref_subjects = 11;</code>
     */
    private $not_pref_subjects;
    /**
     * Generated from protobuf field <code>int32 pref_lineup_duration = 12;</code>
     */
    protected $pref_lineup_duration = 0;
    /**
     * Generated from protobuf field <code>repeated string news_markets = 13;</code>
     */
    private $news_markets;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $pref_source_entity
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $not_pref_source_entity
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $pref_highlevel_subject
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $not_pref_highlevel_subject
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $pref_people_organization
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $not_pref_people_organization
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $pref_geo
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $not_pref_geo
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $pref_personal_interest
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $pref_subjects
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $not_pref_subjects
     *     @type int $pref_lineup_duration
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $news_markets
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string pref_source_entity = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrefSourceEntity()
    {
        return $this->pref_source_entity;
    }

    /**
     * Generated from protobuf field <code>repeated string pref_source_entity = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrefSourceEntity($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->pref_source_entity = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string not_pref_source_entity = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNotPrefSourceEntity()
    {
        return $this->not_pref_source_entity;
    }

    /**
     * Generated from protobuf field <code>repeated string not_pref_source_entity = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNotPrefSourceEntity($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->not_pref_source_entity = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string pref_highlevel_subject = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrefHighlevelSubject()
    {
        return $this->pref_highlevel_subject;
    }

    /**
     * Generated from protobuf field <code>repeated string pref_highlevel_subject = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrefHighlevelSubject($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->pref_highlevel_subject = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string not_pref_highlevel_subject = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNotPrefHighlevelSubject()
    {
        return $this->not_pref_highlevel_subject;
    }

    /**
     * Generated from protobuf field <code>repeated string not_pref_highlevel_subject = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNotPrefHighlevelSubject($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->not_pref_highlevel_subject = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string pref_people_organization = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrefPeopleOrganization()
    {
        return $this->pref_people_organization;
    }

    /**
     * Generated from protobuf field <code>repeated string pref_people_organization = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrefPeopleOrganization($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->pref_people_organization = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string not_pref_people_organization = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNotPrefPeopleOrganization()
    {
        return $this->not_pref_people_organization;
    }

    /**
     * Generated from protobuf field <code>repeated string not_pref_people_organization = 6;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNotPrefPeopleOrganization($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->not_pref_people_organization = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string pref_geo = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrefGeo()
    {
        return $this->pref_geo;
    }

    /**
     * Generated from protobuf field <code>repeated string pref_geo = 7;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrefGeo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->pref_geo = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string not_pref_geo = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNotPrefGeo()
    {
        return $this->not_pref_geo;
    }

    /**
     * Generated from protobuf field <code>repeated string not_pref_geo = 8;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNotPrefGeo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->not_pref_geo = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string pref_personal_interest = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrefPersonalInterest()
    {
        return $this->pref_personal_interest;
    }

    /**
     * Generated from protobuf field <code>repeated string pref_personal_interest = 9;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrefPersonalInterest($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->pref_personal_interest = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string pref_subjects = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrefSubjects()
    {
        return $this->pref_subjects;
    }

    /**
     * Generated from protobuf field <code>repeated string pref_subjects = 10;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrefSubjects($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->pref_subjects = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string not_pref_subjects = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNotPrefSubjects()
    {
        return $this->not_pref_subjects;
    }

    /**
     * Generated from protobuf field <code>repeated string not_pref_subjects = 11;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNotPrefSubjects($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->not_pref_subjects = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pref_lineup_duration = 12;</code>
     * @return int
     */
    public function getPrefLineupDuration()
    {
        return $this->pref_lineup_duration;
    }

    /**
     * Generated from protobuf field <code>int32 pref_lineup_duration = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setPrefLineupDuration($var)
    {
        GPBUtil::checkInt32($var);
        $this->pref_lineup_duration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string news_markets = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNewsMarkets()
    {
        return $this->news_markets;
    }

    /**
     * Generated from protobuf field <code>repeated string news_markets = 13;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNewsMarkets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->news_markets = $arr;

        return $this;
    }

}

