<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>endpoints.events.GetSourcesReplyHelper</code>
 */
class GetSourcesReplyHelper extends \Google\Protobuf\Internal\Message
{
    /**
     *Source Name
     *
     * Generated from protobuf field <code>string source_name = 1;</code>
     */
    protected $source_name = '';
    /**
     *List of DMA
     *
     * Generated from protobuf field <code>repeated string news_market = 2;</code>
     */
    private $news_market;
    /**
     * Generated from protobuf field <code>string vnp_id = 6;</code>
     */
    protected $vnp_id = '';
    protected $num_oneof;
    protected $datetime_oneof;
    protected $created_by_oneof;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $source_name
     *          Source Name
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $news_market
     *          List of DMA
     *     @type int $number_of_videos
     *          Number of all videos related to source
     *     @type string $datetime
     *          Source creation date
     *     @type string $created_by
     *          Creator Name
     *     @type string $vnp_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     *Source Name
     *
     * Generated from protobuf field <code>string source_name = 1;</code>
     * @return string
     */
    public function getSourceName()
    {
        return $this->source_name;
    }

    /**
     *Source Name
     *
     * Generated from protobuf field <code>string source_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_name = $var;

        return $this;
    }

    /**
     *List of DMA
     *
     * Generated from protobuf field <code>repeated string news_market = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNewsMarket()
    {
        return $this->news_market;
    }

    /**
     *List of DMA
     *
     * Generated from protobuf field <code>repeated string news_market = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNewsMarket($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->news_market = $arr;

        return $this;
    }

    /**
     *Number of all videos related to source
     *
     * Generated from protobuf field <code>int32 number_of_videos = 3;</code>
     * @return int
     */
    public function getNumberOfVideos()
    {
        return $this->readOneof(3);
    }

    public function hasNumberOfVideos()
    {
        return $this->hasOneof(3);
    }

    /**
     *Number of all videos related to source
     *
     * Generated from protobuf field <code>int32 number_of_videos = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setNumberOfVideos($var)
    {
        GPBUtil::checkInt32($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     *Source creation date
     *
     * Generated from protobuf field <code>string datetime = 4;</code>
     * @return string
     */
    public function getDatetime()
    {
        return $this->readOneof(4);
    }

    public function hasDatetime()
    {
        return $this->hasOneof(4);
    }

    /**
     *Source creation date
     *
     * Generated from protobuf field <code>string datetime = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDatetime($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     *Creator Name
     *
     * Generated from protobuf field <code>string created_by = 5;</code>
     * @return string
     */
    public function getCreatedBy()
    {
        return $this->readOneof(5);
    }

    public function hasCreatedBy()
    {
        return $this->hasOneof(5);
    }

    /**
     *Creator Name
     *
     * Generated from protobuf field <code>string created_by = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedBy($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vnp_id = 6;</code>
     * @return string
     */
    public function getVnpId()
    {
        return $this->vnp_id;
    }

    /**
     * Generated from protobuf field <code>string vnp_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setVnpId($var)
    {
        GPBUtil::checkString($var, True);
        $this->vnp_id = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getNumOneof()
    {
        return $this->whichOneof("num_oneof");
    }

    /**
     * @return string
     */
    public function getDatetimeOneof()
    {
        return $this->whichOneof("datetime_oneof");
    }

    /**
     * @return string
     */
    public function getCreatedByOneof()
    {
        return $this->whichOneof("created_by_oneof");
    }

}

