<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The reply containing the message from VNE.
 *Sample Reply body:
 *{'sources': [
 * {'source_name': 'ABC7',
 * 'DMA_list': ['San Jose', 'Los Angeles', 'New York'],
 * 'number_of_videos': 237,
 * 'datetime': '2020-12-14T05:13:05.000000000',
 * 'created_by': 'william'}, ...
 * ]}
 *
 * Generated from protobuf message <code>endpoints.events.GetSourcesReply</code>
 */
class GetSourcesReply extends \Google\Protobuf\Internal\Message
{
    /**
     *List of all sources
     *
     * Generated from protobuf field <code>repeated .endpoints.events.GetSourcesReplyHelper sources = 1;</code>
     */
    private $sources;
    /**
     * Generated from protobuf field <code>string status = 3;</code>
     */
    protected $status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Endpoints\Events\GetSourcesReplyHelper[]|\Google\Protobuf\Internal\RepeatedField $sources
     *          List of all sources
     *     @type string $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     *List of all sources
     *
     * Generated from protobuf field <code>repeated .endpoints.events.GetSourcesReplyHelper sources = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSources()
    {
        return $this->sources;
    }

    /**
     *List of all sources
     *
     * Generated from protobuf field <code>repeated .endpoints.events.GetSourcesReplyHelper sources = 1;</code>
     * @param \Endpoints\Events\GetSourcesReplyHelper[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSources($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Endpoints\Events\GetSourcesReplyHelper::class);
        $this->sources = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 3;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

}

