<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>endpoints.events.GetSegmentsListReply</code>
 */
class GetSegmentsListReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .endpoints.events.GetSegmentsListReplyHelper segment_list = 1;</code>
     */
    private $segment_list;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Endpoints\Events\GetSegmentsListReplyHelper[]|\Google\Protobuf\Internal\RepeatedField $segment_list
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .endpoints.events.GetSegmentsListReplyHelper segment_list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSegmentList()
    {
        return $this->segment_list;
    }

    /**
     * Generated from protobuf field <code>repeated .endpoints.events.GetSegmentsListReplyHelper segment_list = 1;</code>
     * @param \Endpoints\Events\GetSegmentsListReplyHelper[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSegmentList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Endpoints\Events\GetSegmentsListReplyHelper::class);
        $this->segment_list = $arr;

        return $this;
    }

}

