<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The reply containing the message from VNE.
 *Sample Reply body:
 *{
 * 'tags': ['ronald reagan', 'arsenal', 'ronaldo', 'cristiano ronaldo', 'mcdonald']
 * }
 *
 * Generated from protobuf message <code>endpoints.events.GetTagsReply</code>
 */
class GetTagsReply extends \Google\Protobuf\Internal\Message
{
    /**
     *List of tags
     *
     * Generated from protobuf field <code>repeated string tags = 1;</code>
     */
    private $tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $tags
     *          List of tags
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     *List of tags
     *
     * Generated from protobuf field <code>repeated string tags = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     *List of tags
     *
     * Generated from protobuf field <code>repeated string tags = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

}

