<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The reply containing the message from VNE.
 *Sample Reply body:
 *{
 * 'number_of_stories': [5498, 7256, 7323, 4877, 7320, 7313, 4896]
 * }
 *
 * Generated from protobuf message <code>endpoints.events.GetUserStoryReply</code>
 */
class GetUserStoryReply extends \Google\Protobuf\Internal\Message
{
    /**
     *List of story id
     *
     * Generated from protobuf field <code>repeated int32 number_of_stories = 1;</code>
     */
    private $number_of_stories;
    /**
     * Generated from protobuf field <code>string status = 3;</code>
     */
    protected $status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $number_of_stories
     *          List of story id
     *     @type string $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     *List of story id
     *
     * Generated from protobuf field <code>repeated int32 number_of_stories = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNumberOfStories()
    {
        return $this->number_of_stories;
    }

    /**
     *List of story id
     *
     * Generated from protobuf field <code>repeated int32 number_of_stories = 1;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNumberOfStories($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->number_of_stories = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 3;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

}

