<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>endpoints.events.LocalDropInsHelper</code>
 */
class LocalDropInsHelper extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string vnp_source_id = 1;</code>
     */
    protected $vnp_source_id = '';
    /**
     * Generated from protobuf field <code>string title = 2;</code>
     */
    protected $title = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $vnp_source_id
     *     @type string $title
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string vnp_source_id = 1;</code>
     * @return string
     */
    public function getVnpSourceId()
    {
        return $this->vnp_source_id;
    }

    /**
     * Generated from protobuf field <code>string vnp_source_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVnpSourceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->vnp_source_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

}

