<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *VNP will send all the lineups lists with pagination.
 *Sample Reply body:
 *{
 * 'lineups': [
 *  {'lineup_id': 'a8715764-fd41-42cc-ba2e-24ab4bc152a7',
 *   'story_ids': [4677, 7343, 4619, 4583, 7324, 4695, 1534, 4713, ...]},...
 *  ]
 *}
 *
 * Generated from protobuf message <code>endpoints.events.ReSyncReply</code>
 */
class ReSyncReply extends \Google\Protobuf\Internal\Message
{
    /**
     *List of all lineups with story ids
     *
     * Generated from protobuf field <code>repeated .endpoints.events.ReSyncReplyHelper lineups = 1;</code>
     */
    private $lineups;
    /**
     * Generated from protobuf field <code>string status = 3;</code>
     */
    protected $status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Endpoints\Events\ReSyncReplyHelper[]|\Google\Protobuf\Internal\RepeatedField $lineups
     *          List of all lineups with story ids
     *     @type string $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     *List of all lineups with story ids
     *
     * Generated from protobuf field <code>repeated .endpoints.events.ReSyncReplyHelper lineups = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLineups()
    {
        return $this->lineups;
    }

    /**
     *List of all lineups with story ids
     *
     * Generated from protobuf field <code>repeated .endpoints.events.ReSyncReplyHelper lineups = 1;</code>
     * @param \Endpoints\Events\ReSyncReplyHelper[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLineups($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Endpoints\Events\ReSyncReplyHelper::class);
        $this->lineups = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 3;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

}

