<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *VNP can send a request to update the lineups table by sending a request to get all the lineups of each user.
 *Sample Request body:
 *{
 * 'first_lineups:100,
 * 'skip': 2000,
 *}
 *
 * Generated from protobuf message <code>endpoints.events.ReSyncRequest</code>
 */
class ReSyncRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *The number of lineups we requested
     *
     * Generated from protobuf field <code>int32 first_lineups = 1;</code>
     */
    protected $first_lineups = 0;
    /**
     *The number of lineups we skipped
     *
     * Generated from protobuf field <code>int32 skip = 2;</code>
     */
    protected $skip = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $first_lineups
     *          The number of lineups we requested
     *     @type int $skip
     *          The number of lineups we skipped
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     *The number of lineups we requested
     *
     * Generated from protobuf field <code>int32 first_lineups = 1;</code>
     * @return int
     */
    public function getFirstLineups()
    {
        return $this->first_lineups;
    }

    /**
     *The number of lineups we requested
     *
     * Generated from protobuf field <code>int32 first_lineups = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFirstLineups($var)
    {
        GPBUtil::checkInt32($var);
        $this->first_lineups = $var;

        return $this;
    }

    /**
     *The number of lineups we skipped
     *
     * Generated from protobuf field <code>int32 skip = 2;</code>
     * @return int
     */
    public function getSkip()
    {
        return $this->skip;
    }

    /**
     *The number of lineups we skipped
     *
     * Generated from protobuf field <code>int32 skip = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSkip($var)
    {
        GPBUtil::checkInt32($var);
        $this->skip = $var;

        return $this;
    }

}

