<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The reply containing the message from VNE.
 *
 * Generated from protobuf message <code>endpoints.events.SegmentsHelper</code>
 */
class SegmentsHelper extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string story_id = 1;</code>
     */
    protected $story_id = '';
    /**
     * Generated from protobuf field <code>string segment = 2;</code>
     */
    protected $segment = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $story_id
     *     @type string $segment
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string story_id = 1;</code>
     * @return string
     */
    public function getStoryId()
    {
        return $this->story_id;
    }

    /**
     * Generated from protobuf field <code>string story_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStoryId($var)
    {
        GPBUtil::checkString($var, True);
        $this->story_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string segment = 2;</code>
     * @return string
     */
    public function getSegment()
    {
        return $this->segment;
    }

    /**
     * Generated from protobuf field <code>string segment = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSegment($var)
    {
        GPBUtil::checkString($var, True);
        $this->segment = $var;

        return $this;
    }

}

