<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>endpoints.events.SegmentCountHelper</code>
 */
class SegmentCountHelper extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string segment = 1;</code>
     */
    protected $segment = '';
    /**
     * Generated from protobuf field <code>int32 count = 2;</code>
     */
    protected $count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $segment
     *     @type int $count
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string segment = 1;</code>
     * @return string
     */
    public function getSegment()
    {
        return $this->segment;
    }

    /**
     * Generated from protobuf field <code>string segment = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSegment($var)
    {
        GPBUtil::checkString($var, True);
        $this->segment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 count = 2;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>int32 count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->count = $var;

        return $this;
    }

}

