<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

if (false) {
    /**
     * This class is deprecated. Use Endpoints\Events\UserInteractionRequest\li instead.
     * @deprecated
     */
    class UserInteractionRequest_li {}
}
class_exists(UserInteractionRequest\li::class);
@trigger_error('Endpoints\Events\UserInteractionRequest_li is deprecated and will be removed in the next major release. Use Endpoints\Events\UserInteractionRequest\li instead', E_USER_DEPRECATED);

