<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>endpoints.events.UserInteractionRequest</code>
 */
class UserInteractionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .endpoints.events.UserInteractionRequest.li> pair = 1;</code>
     */
    private $pair;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $pair
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .endpoints.events.UserInteractionRequest.li> pair = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getPair()
    {
        return $this->pair;
    }

    /**
     * Generated from protobuf field <code>map<string, .endpoints.events.UserInteractionRequest.li> pair = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setPair($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Endpoints\Events\UserInteractionRequest\li::class);
        $this->pair = $arr;

        return $this;
    }

}

