<?php

namespace App\Enums;

class UserRoleEnum extends BasicEnum
{
    const ROLE_USER = 'ROLE_USER';
    const ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN';
    const ROLE_SUB_USER = 'ROLE_SUB_USER';
    const ROLE_MNGT_SUB_USER = 'ROLE_MNGT_SUB_USER';
    const ROLE_SEE_ALL_SOURCE_VIDEO = 'ROLE_SEE_ALL_SOURCE_VIDEO';
    const ROLE_SEE_OWN_SOURCE_VIDEO = 'ROLE_SEE_OWN_SOURCE_VIDEO';
    const ROLE_MNGT_SOURCE_VIDEO = 'ROLE_MNGT_SOURCE_VIDEO';
    const ROLE_MNGT_SOURCE_VIDEO_MARKUP_INTERFACE = 'ROLE_MNGT_SOURCE_VIDEO_MARKUP_INTERFACE';
    const ROLE_SEE_STORIES = 'ROLE_SEE_STORIES';
    const ROLE_MNGT_STORIES = 'ROLE_MNGT_STORIES';
    const ROLE_MNGT_QA = 'ROLE_MNGT_QA';
    const ROLE_MNGT_FTP_SERVER = 'ROLE_MNGT_FTP_SERVER';
    const ROLE_VIEW_LINEUPS = 'ROLE_VIEW_LINEUPS';
    const ROLE_MNGT_SUBSCRIPTIONS = 'ROLE_MNGT_SUBSCRIPTIONS';
    const ROLE_MNGT_PAYMENTS = 'ROLE_MNGT_PAYMENTS';
    const ROLE_MNGT_END_USERS = 'ROLE_MNGT_END_USERS';
    const ROLE_MNGT_ADS = 'ROLE_MNGT_ADS';

}
