<?php

namespace App\Enums;

class VodStatusEnum extends BasicEnum
{
    const INITIALIZED = 'INITIALIZED';
    const PROCESSING_FAILED = 'PROCESSING FAILED';
    const TRANSCODING_IN_A_QUEUE = 'TRANSCODING IN A QUEUE';
    const TRANSCODING_IN_PROGRESS = 'TRANSCODING IN PROGRESS';
    const TRANSCODING_DONE = 'TRANSCODING_DONE';
    const ERROR_IN_TRANSCODING = 'ERROR IN TRANSCODING';
    const TRANSCODING_CANCELED = 'TRANSCODING CANCELED';
    const READY = 'READY';
}
