<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events\GetDMAReply;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>endpoints.events.GetDMAReply.DMA</code>
 */
class DMA extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string dma_name = 1;</code>
     */
    protected $dma_name = '';
    /**
     * Generated from protobuf field <code>repeated .endpoints.events.GetDMAReply.DMA.County county_list = 2;</code>
     */
    private $county_list;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $dma_name
     *     @type \Endpoints\Events\GetDMAReply\DMA\County[]|\Google\Protobuf\Internal\RepeatedField $county_list
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string dma_name = 1;</code>
     * @return string
     */
    public function getDmaName()
    {
        return $this->dma_name;
    }

    /**
     * Generated from protobuf field <code>string dma_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDmaName($var)
    {
        GPBUtil::checkString($var, True);
        $this->dma_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .endpoints.events.GetDMAReply.DMA.County county_list = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCountyList()
    {
        return $this->county_list;
    }

    /**
     * Generated from protobuf field <code>repeated .endpoints.events.GetDMAReply.DMA.County county_list = 2;</code>
     * @param \Endpoints\Events\GetDMAReply\DMA\County[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCountyList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Endpoints\Events\GetDMAReply\DMA\County::class);
        $this->county_list = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(DMA::class, \Endpoints\Events\GetDMAReply_DMA::class);

