<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Endpoints\Events\GetDMAReply\DMA;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>endpoints.events.GetDMAReply.DMA.County</code>
 */
class County extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string county_id = 1;</code>
     */
    protected $county_id = '';
    /**
     * Generated from protobuf field <code>string county_name = 2;</code>
     */
    protected $county_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $county_id
     *     @type string $county_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string county_id = 1;</code>
     * @return string
     */
    public function getCountyId()
    {
        return $this->county_id;
    }

    /**
     * Generated from protobuf field <code>string county_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCountyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->county_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string county_name = 2;</code>
     * @return string
     */
    public function getCountyName()
    {
        return $this->county_name;
    }

    /**
     * Generated from protobuf field <code>string county_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCountyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->county_name = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(County::class, \Endpoints\Events\GetDMAReply_DMA_County::class);

