<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The reply containing the message from VNE.
 *Sample Reply body:
 *{
 * 'lineup_id': 'b6ef0f14-8d31-4106-8722-6ecf0cbd0b64',
 * 'story_ids': [7146, 7145, 7951, 8394, 8392]
 * }
 *
 * Generated from protobuf message <code>CreateLineupReply</code>
 */
class CreateLineupReply extends \Google\Protobuf\Internal\Message
{
    /**
     *Unique lineup ID (UUID)
     *
     * Generated from protobuf field <code>string lineup_id = 1;</code>
     */
    protected $lineup_id = '';
    /**
     *list of story id
     *
     * Generated from protobuf field <code>repeated int32 story_ids = 2;</code>
     */
    private $story_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $lineup_id
     *          Unique lineup ID (UUID)
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $story_ids
     *          list of story id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     *Unique lineup ID (UUID)
     *
     * Generated from protobuf field <code>string lineup_id = 1;</code>
     * @return string
     */
    public function getLineupId()
    {
        return $this->lineup_id;
    }

    /**
     *Unique lineup ID (UUID)
     *
     * Generated from protobuf field <code>string lineup_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLineupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->lineup_id = $var;

        return $this;
    }

    /**
     *list of story id
     *
     * Generated from protobuf field <code>repeated int32 story_ids = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStoryIds()
    {
        return $this->story_ids;
    }

    /**
     *list of story id
     *
     * Generated from protobuf field <code>repeated int32 story_ids = 2;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStoryIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->story_ids = $arr;

        return $this;
    }

}

