<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * When a user on the platforms of VNP want to see his/her lineup, VNP will send a request to VNE via GRPC.
 *Sample Request body:
 *{
 * 'user_id': '8557f811-69e9-4379-912f-4ddbacc3da00',
 * 'ip_address': '122.112.113.114',
 * 'preferred_lineup_duration': 5,
 * 'latitude': 38.917032,
 * 'longitude': -95.06455
 * }
 *
 * Generated from protobuf message <code>CreateLineupRequest</code>
 */
class CreateLineupRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *Unique user ID (UUID)
     *
     * Generated from protobuf field <code>string user_id = 1;</code>
     */
    protected $user_id = '';
    /**
     *User IP Address
     *
     * Generated from protobuf field <code>string ip_address = 2;</code>
     */
    protected $ip_address = '';
    /**
     * User preferred lineup duration
     *
     * Generated from protobuf field <code>int32 preferred_lineup_duration = 3;</code>
     */
    protected $preferred_lineup_duration = 0;
    /**
     *Geographic coordinate that specifies the north–south position
     *
     * Generated from protobuf field <code>float latitude = 4;</code>
     */
    protected $latitude = 0.0;
    /**
     *Geographic coordinate that specifies the east–west position
     *
     * Generated from protobuf field <code>float longitude = 5;</code>
     */
    protected $longitude = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *          Unique user ID (UUID)
     *     @type string $ip_address
     *          User IP Address
     *     @type int $preferred_lineup_duration
     *           User preferred lineup duration
     *     @type float $latitude
     *          Geographic coordinate that specifies the north–south position
     *     @type float $longitude
     *          Geographic coordinate that specifies the east–west position
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     *Unique user ID (UUID)
     *
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *Unique user ID (UUID)
     *
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     *User IP Address
     *
     * Generated from protobuf field <code>string ip_address = 2;</code>
     * @return string
     */
    public function getIpAddress()
    {
        return $this->ip_address;
    }

    /**
     *User IP Address
     *
     * Generated from protobuf field <code>string ip_address = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIpAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip_address = $var;

        return $this;
    }

    /**
     * User preferred lineup duration
     *
     * Generated from protobuf field <code>int32 preferred_lineup_duration = 3;</code>
     * @return int
     */
    public function getPreferredLineupDuration()
    {
        return $this->preferred_lineup_duration;
    }

    /**
     * User preferred lineup duration
     *
     * Generated from protobuf field <code>int32 preferred_lineup_duration = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPreferredLineupDuration($var)
    {
        GPBUtil::checkInt32($var);
        $this->preferred_lineup_duration = $var;

        return $this;
    }

    /**
     *Geographic coordinate that specifies the north–south position
     *
     * Generated from protobuf field <code>float latitude = 4;</code>
     * @return float
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     *Geographic coordinate that specifies the north–south position
     *
     * Generated from protobuf field <code>float latitude = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setLatitude($var)
    {
        GPBUtil::checkFloat($var);
        $this->latitude = $var;

        return $this;
    }

    /**
     *Geographic coordinate that specifies the east–west position
     *
     * Generated from protobuf field <code>float longitude = 5;</code>
     * @return float
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     *Geographic coordinate that specifies the east–west position
     *
     * Generated from protobuf field <code>float longitude = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setLongitude($var)
    {
        GPBUtil::checkFloat($var);
        $this->longitude = $var;

        return $this;
    }

}

