<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *When a user want to remove his/her account, VNP will send a request to VNE to remove the user.
 *BTW, VNE only removes personal information, but his/her preferences would be useful for story recomendation to fresh users.
 *Sample Request body:
 *{
 *'user_id':'8557f811-69e9-4379-912f-4ddbacc3da00',
 *'remove_type:'Inactive'
 *}
 *
 * Generated from protobuf message <code>DeleteUserRequest</code>
 */
class DeleteUserRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *Unique user ID (UUID)
     *
     * Generated from protobuf field <code>string user_id = 1;</code>
     */
    protected $user_id = '';
    /**
     *Remove type
     *
     * Generated from protobuf field <code>string remove_type = 2;</code>
     */
    protected $remove_type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *          Unique user ID (UUID)
     *     @type string $remove_type
     *          Remove type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     *Unique user ID (UUID)
     *
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *Unique user ID (UUID)
     *
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     *Remove type
     *
     * Generated from protobuf field <code>string remove_type = 2;</code>
     * @return string
     */
    public function getRemoveType()
    {
        return $this->remove_type;
    }

    /**
     *Remove type
     *
     * Generated from protobuf field <code>string remove_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRemoveType($var)
    {
        GPBUtil::checkString($var, True);
        $this->remove_type = $var;

        return $this;
    }

}

