<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The reply containing the message from VNE.
 *Sample Reply body:
 *{
 * 'preferences': ['pref_source_entity', 'not_pref_source_entity', 'pref_subject', 'not_pref_subject', 'pref_words_entity', 'not_pref_words_entity', 'pref_location', 'not_pref_location']
 *}
 *
 * Generated from protobuf message <code>GetPreferencesReply</code>
 */
class GetPreferencesReply extends \Google\Protobuf\Internal\Message
{
    /**
     *List of user preferences
     *
     * Generated from protobuf field <code>repeated string preferences = 1;</code>
     */
    private $preferences;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $preferences
     *          List of user preferences
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     *List of user preferences
     *
     * Generated from protobuf field <code>repeated string preferences = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPreferences()
    {
        return $this->preferences;
    }

    /**
     *List of user preferences
     *
     * Generated from protobuf field <code>repeated string preferences = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPreferences($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->preferences = $arr;

        return $this;
    }

}

