<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The reply containing the message from VNE.
 *Sample Reply body:
 *{
 *'story_ids':["4661a552-a0e8-43c9-a916-23940faddc96"]
 *}
 *
 * Generated from protobuf message <code>GetSimilarStoriesReply</code>
 */
class GetSimilarStoriesReply extends \Google\Protobuf\Internal\Message
{
    /**
     *List of story id
     *
     * Generated from protobuf field <code>repeated string story_ids = 1;</code>
     */
    private $story_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $story_ids
     *          List of story id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     *List of story id
     *
     * Generated from protobuf field <code>repeated string story_ids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStoryIds()
    {
        return $this->story_ids;
    }

    /**
     *List of story id
     *
     * Generated from protobuf field <code>repeated string story_ids = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStoryIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->story_ids = $arr;

        return $this;
    }

}

