<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *A button is surfaced on VNP to user when viewing the story, when clicked asks VNE for specialized lineup and similar stories.
 *Sample Request body:
 *{
 * 'story_id': 'f31ce620-ac1e-4a1b-aa14-82a1ec3bd417',
 * 'ip_address': '122.112.113.114',
 * 'preferred_lineup_duration': 5,
 * 'latitude': 38.917032,
 * 'longitude': -95.06455
 * }
 *
 * Generated from protobuf message <code>GetSimilarStoriesRequest</code>
 */
class GetSimilarStoriesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *Unique story ID (UUID)
     *
     * Generated from protobuf field <code>string story_id = 1;</code>
     */
    protected $story_id = '';
    /**
     *IP address
     *
     * Generated from protobuf field <code>string ip_address = 2;</code>
     */
    protected $ip_address = '';
    /**
     *Preferred lineup duration
     *
     * Generated from protobuf field <code>int32 preferred_lineup_duration = 3;</code>
     */
    protected $preferred_lineup_duration = 0;
    /**
     *Geographic coordinate that specifies the north–south position
     *
     * Generated from protobuf field <code>float latitude = 4;</code>
     */
    protected $latitude = 0.0;
    /**
     *Geographic coordinate that specifies the east–west position
     *
     * Generated from protobuf field <code>float longitude = 5;</code>
     */
    protected $longitude = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $story_id
     *          Unique story ID (UUID)
     *     @type string $ip_address
     *          IP address
     *     @type int $preferred_lineup_duration
     *          Preferred lineup duration
     *     @type float $latitude
     *          Geographic coordinate that specifies the north–south position
     *     @type float $longitude
     *          Geographic coordinate that specifies the east–west position
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     *Unique story ID (UUID)
     *
     * Generated from protobuf field <code>string story_id = 1;</code>
     * @return string
     */
    public function getStoryId()
    {
        return $this->story_id;
    }

    /**
     *Unique story ID (UUID)
     *
     * Generated from protobuf field <code>string story_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStoryId($var)
    {
        GPBUtil::checkString($var, True);
        $this->story_id = $var;

        return $this;
    }

    /**
     *IP address
     *
     * Generated from protobuf field <code>string ip_address = 2;</code>
     * @return string
     */
    public function getIpAddress()
    {
        return $this->ip_address;
    }

    /**
     *IP address
     *
     * Generated from protobuf field <code>string ip_address = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIpAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip_address = $var;

        return $this;
    }

    /**
     *Preferred lineup duration
     *
     * Generated from protobuf field <code>int32 preferred_lineup_duration = 3;</code>
     * @return int
     */
    public function getPreferredLineupDuration()
    {
        return $this->preferred_lineup_duration;
    }

    /**
     *Preferred lineup duration
     *
     * Generated from protobuf field <code>int32 preferred_lineup_duration = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPreferredLineupDuration($var)
    {
        GPBUtil::checkInt32($var);
        $this->preferred_lineup_duration = $var;

        return $this;
    }

    /**
     *Geographic coordinate that specifies the north–south position
     *
     * Generated from protobuf field <code>float latitude = 4;</code>
     * @return float
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     *Geographic coordinate that specifies the north–south position
     *
     * Generated from protobuf field <code>float latitude = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setLatitude($var)
    {
        GPBUtil::checkFloat($var);
        $this->latitude = $var;

        return $this;
    }

    /**
     *Geographic coordinate that specifies the east–west position
     *
     * Generated from protobuf field <code>float longitude = 5;</code>
     * @return float
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     *Geographic coordinate that specifies the east–west position
     *
     * Generated from protobuf field <code>float longitude = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setLongitude($var)
    {
        GPBUtil::checkFloat($var);
        $this->longitude = $var;

        return $this;
    }

}

