<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The reply containing the message from VNE.
 *Sample Reply body:
 *{
 * 'story_id': '4661a552-a0e8-43c9-a916-23940faddc96',
 * 'marker_tag': 'JCL',
 * 'vne_tag': 'JCL'}
 *
 * Generated from protobuf message <code>GetStoryTagsReply</code>
 */
class GetStoryTagsReply extends \Google\Protobuf\Internal\Message
{
    /**
     *Unique story ID (UUID)
     *
     * Generated from protobuf field <code>string story_id = 1;</code>
     */
    protected $story_id = '';
    /**
     *Marker Tag
     *
     * Generated from protobuf field <code>string marker_tag = 2;</code>
     */
    protected $marker_tag = '';
    /**
     *VNE Tag
     *
     * Generated from protobuf field <code>string vne_tag = 3;</code>
     */
    protected $vne_tag = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $story_id
     *          Unique story ID (UUID)
     *     @type string $marker_tag
     *          Marker Tag
     *     @type string $vne_tag
     *          VNE Tag
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     *Unique story ID (UUID)
     *
     * Generated from protobuf field <code>string story_id = 1;</code>
     * @return string
     */
    public function getStoryId()
    {
        return $this->story_id;
    }

    /**
     *Unique story ID (UUID)
     *
     * Generated from protobuf field <code>string story_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStoryId($var)
    {
        GPBUtil::checkString($var, True);
        $this->story_id = $var;

        return $this;
    }

    /**
     *Marker Tag
     *
     * Generated from protobuf field <code>string marker_tag = 2;</code>
     * @return string
     */
    public function getMarkerTag()
    {
        return $this->marker_tag;
    }

    /**
     *Marker Tag
     *
     * Generated from protobuf field <code>string marker_tag = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMarkerTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->marker_tag = $var;

        return $this;
    }

    /**
     *VNE Tag
     *
     * Generated from protobuf field <code>string vne_tag = 3;</code>
     * @return string
     */
    public function getVneTag()
    {
        return $this->vne_tag;
    }

    /**
     *VNE Tag
     *
     * Generated from protobuf field <code>string vne_tag = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVneTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->vne_tag = $var;

        return $this;
    }

}

