<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *When VNP want to get the all available geo, subject, entities (people or organizations name) and main subjects on the VNE,
 *it can use this endpoint.
 *Sample Request:
 *{
 *'requested_tag_type':'Entity',
 *'search_string':'ronaldo'
 *}
 *
 * Generated from protobuf message <code>GetTagsRequest</code>
 */
class GetTagsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Requested tag
     *
     * Generated from protobuf field <code>string requested_tag_type = 1;</code>
     */
    protected $requested_tag_type = '';
    /**
     * Search string
     *
     * Generated from protobuf field <code>string search_string = 2;</code>
     */
    protected $search_string = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $requested_tag_type
     *           Requested tag
     *     @type string $search_string
     *           Search string
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Requested tag
     *
     * Generated from protobuf field <code>string requested_tag_type = 1;</code>
     * @return string
     */
    public function getRequestedTagType()
    {
        return $this->requested_tag_type;
    }

    /**
     * Requested tag
     *
     * Generated from protobuf field <code>string requested_tag_type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestedTagType($var)
    {
        GPBUtil::checkString($var, True);
        $this->requested_tag_type = $var;

        return $this;
    }

    /**
     * Search string
     *
     * Generated from protobuf field <code>string search_string = 2;</code>
     * @return string
     */
    public function getSearchString()
    {
        return $this->search_string;
    }

    /**
     * Search string
     *
     * Generated from protobuf field <code>string search_string = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSearchString($var)
    {
        GPBUtil::checkString($var, True);
        $this->search_string = $var;

        return $this;
    }

}

