<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *VNP sends lineup ID along with interaction data:
 *positive: comment, share, preferred, feedback
 *negative: discard
 *positive/negative: watch time
 *
 * Generated from protobuf message <code>UserInteractionRequest</code>
 */
class UserInteractionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string request = 1;</code>
     */
    protected $request = '';
    /**
     * Generated from protobuf field <code>string event = 2;</code>
     */
    protected $event = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $request
     *     @type string $event
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string request = 1;</code>
     * @return string
     */
    public function getRequest()
    {
        return $this->request;
    }

    /**
     * Generated from protobuf field <code>string request = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkString($var, True);
        $this->request = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string event = 2;</code>
     * @return string
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * Generated from protobuf field <code>string event = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEvent($var)
    {
        GPBUtil::checkString($var, True);
        $this->event = $var;

        return $this;
    }

}

